/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2017-9-24:  9h:21m
**
*/

var Wormlike_statmp74

var Wormlike_statmp75

var Wormlike_statmp76

var Wormlike_statmp89

function
Wormlike_patsfun_28__closurerize(env0)
{
  return [function(cenv, arg0, arg1) { return Wormlike_patsfun_28(cenv[1], arg0, arg1); }, env0];
}


function
Wormlike_patsfun_32__closurerize(env0)
{
  return [function(cenv, arg0, arg1) { return Wormlike_patsfun_32(cenv[1], arg0, arg1); }, env0];
}


function
Wormlike_patsfun_35__closurerize(env0, env1, env2)
{
  return [function(cenv, arg0) { return Wormlike_patsfun_35(cenv[1], cenv[2], cenv[3], arg0); }, env0, env1, env2];
}


function
Wormlike_patsfun_40__closurerize(env0)
{
  return [function(cenv) { return Wormlike_patsfun_40(cenv[1]); }, env0];
}


function
Wormlike_patsfun_58__58__1__closurerize(env0, env1)
{
  return [function(cenv) { return Wormlike_patsfun_58__58__1(cenv[1], cenv[2]); }, env0, env1];
}


function
Wormlike_patsfun_64__64__1__closurerize(env0, env1)
{
  return [function(cenv, arg0) { return Wormlike_patsfun_64__64__1(cenv[1], cenv[2], arg0); }, env0, env1];
}


function
Wormlike_x_dec_0(arg0)
{
//
// knd = 0
  var tmpret0
  var tmp1
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_x_dec_0
  tmp1 = ats2jspre_gt_int0_int0(arg0, 0);
  if(tmp1) {
    tmpret0 = ats2jspre_sub_int0_int0(arg0, 1);
  } else {
    tmpret0 = ats2jspre_sub_int1_int1(48, 1);
  } // end-of-if
  return tmpret0;
} // end-of-function


function
Wormlike_x_inc_1(arg0)
{
//
// knd = 0
  var tmpret2
  var tmp3
  var tmp4
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_x_inc_1
  tmp4 = ats2jspre_add_int0_int0(arg0, 1);
  tmp3 = ats2jspre_lt_int0_int0(tmp4, 48);
  if(tmp3) {
    tmpret2 = ats2jspre_add_int0_int0(arg0, 1);
  } else {
    tmpret2 = 0;
  } // end-of-if
  return tmpret2;
} // end-of-function


function
Wormlike_y_dec_2(arg0)
{
//
// knd = 0
  var tmpret5
  var tmp6
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_y_dec_2
  tmp6 = ats2jspre_gt_int0_int0(arg0, 0);
  if(tmp6) {
    tmpret5 = ats2jspre_sub_int0_int0(arg0, 1);
  } else {
    tmpret5 = ats2jspre_sub_int1_int1(48, 1);
  } // end-of-if
  return tmpret5;
} // end-of-function


function
Wormlike_y_inc_3(arg0)
{
//
// knd = 0
  var tmpret7
  var tmp8
  var tmp9
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_y_inc_3
  tmp9 = ats2jspre_add_int0_int0(arg0, 1);
  tmp8 = ats2jspre_lt_int0_int0(tmp9, 48);
  if(tmp8) {
    tmpret7 = ats2jspre_add_int0_int0(arg0, 1);
  } else {
    tmpret7 = 0;
  } // end-of-if
  return tmpret7;
} // end-of-function


function
Wormlike_pos_x_dec_4(arg0)
{
//
// knd = 0
  var tmpret10
  var tmp11
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_pos_x_dec_4
  tmp11 = Wormlike_x_dec_0(arg0[0]);
  tmpret10 = [tmp11, arg0[1]];
  return tmpret10;
} // end-of-function


function
Wormlike_pos_x_inc_5(arg0)
{
//
// knd = 0
  var tmpret12
  var tmp13
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_pos_x_inc_5
  tmp13 = Wormlike_x_inc_1(arg0[0]);
  tmpret12 = [tmp13, arg0[1]];
  return tmpret12;
} // end-of-function


function
Wormlike_pos_y_dec_6(arg0)
{
//
// knd = 0
  var tmpret14
  var tmp15
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_pos_y_dec_6
  tmp15 = Wormlike_y_dec_2(arg0[1]);
  tmpret14 = [arg0[0], tmp15];
  return tmpret14;
} // end-of-function


function
Wormlike_pos_y_inc_7(arg0)
{
//
// knd = 0
  var tmpret16
  var tmp17
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_pos_y_inc_7
  tmp17 = Wormlike_y_inc_3(arg0[1]);
  tmpret16 = [arg0[0], tmp17];
  return tmpret16;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_pos(arg0)
{
//
// knd = 0
  var tmpret18
  var tmp19
  var tmplab, tmplab_js
//
  // __patsflab_wnode_pos
  tmp19 = arg0[0];
  tmpret18 = ats2jspre_ref_get_elt(tmp19);
  return tmpret18;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_tail(arg0)
{
//
// knd = 0
  var tmpret20
  var tmp21
  var tmplab, tmplab_js
//
  // __patsflab_wnode_tail
  tmp21 = arg0[1];
  tmpret20 = ats2jspre_ref_get_elt(tmp21);
  return tmpret20;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_set_pos(arg0, arg1)
{
//
// knd = 0
  var tmp23
  var tmplab, tmplab_js
//
  // __patsflab_wnode_set_pos
  tmp23 = arg0[0];
  ats2jspre_ref_set_elt(tmp23, arg1);
  return/*_void*/;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_set_tail(arg0, arg1)
{
//
// knd = 0
  var tmp25
  var tmplab, tmplab_js
//
  // __patsflab_wnode_set_tail
  tmp25 = arg0[1];
  ats2jspre_ref_set_elt(tmp25, arg1);
  return/*_void*/;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_length(arg0)
{
//
// knd = 0
  var tmpret26
  var tmp27
  var tmp28
  var tmp29
  var tmplab, tmplab_js
//
  // __patsflab_wnode_length
  tmp27 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_tail(arg0);
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab0
      if(ATSCKptriscons(tmp27)) {
        { tmplab_js = 4; break; }
      } // ifthen
      case 2: // __atstmplab1
      tmpret26 = 1;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab2
      case 4: // __atstmplab3
      tmp28 = tmp27[0];
      tmp29 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_length(tmp28);
      tmpret26 = ats2jspre_add_int0_int0(1, tmp29);
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret26;
} // end-of-function


function
Wormlike_wnode_make_pos_13(arg0)
{
//
// knd = 0
  var tmpret30
  var tmp31
  var tmp32
  var tmp33
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_wnode_make_pos_13
  tmp31 = ats2jspre_ref(arg0);
  tmp33 = null;
  tmp32 = ats2jspre_ref(tmp33);
  tmpret30 = [tmp31, tmp32];
  return tmpret30;
} // end-of-function


function
Wormlike_wnode_make_pos_tail_14(arg0, arg1)
{
//
// knd = 0
  var tmpret34
  var tmp35
  var tmp36
  var tmp37
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_wnode_make_pos_tail_14
  tmp35 = ats2jspre_ref(arg0);
  tmp37 = [arg1];
  tmp36 = ats2jspre_ref(tmp37);
  tmpret34 = [tmp35, tmp36];
  return tmpret34;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__worm_remove_last(arg0)
{
//
// knd = 0
  var tmp39
  var tmp40
  var tmp41
  var tmplab, tmplab_js
//
  // __patsflab_worm_remove_last
  tmp40 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_length(arg0);
  tmp39 = ats2jspre_gte_int0_int0(tmp40, 2);
  if(tmp39) {
    tmp41 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__worm_takeout_last(arg0);
    // ATSINSmove_void
  } else {
    // ATSINSmove_void
  } // end-of-if
  return/*_void*/;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__worm_takeout_last(arg0)
{
//
// knd = 0
  var tmpret42
  var tmp48
  var tmp49
  var tmplab, tmplab_js
//
  // __patsflab_worm_takeout_last
  tmp48 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_tail(arg0);
  if(ATSCKptrisnull(tmp48)) {
    ATSINScaseof_fail("/home/asmalldev/Sync/Code/Rosetta/ATS/brownian_tree/DATS_JS/theWorm.dats: 2084(line=143, offs=5) -- 2106(line=143, offs=27)");
  } // ifthen
  tmp49 = tmp48[0];
  tmpret42 = Wormlike_loop_17(arg0, tmp49);
  return tmpret42;
} // end-of-function


function
Wormlike_loop_17(arg0, arg1)
{
//
// knd = 1
  var apy0
  var apy1
  var tmpret43
  var tmp44
  var tmp45
  var tmp47
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_Wormlike_loop_17
    tmp44 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_tail(arg1);
    // ATScaseofseq_beg
    tmplab_js = 1;
    while(true) {
      tmplab = tmplab_js; tmplab_js = 0;
      switch(tmplab) {
        // ATSbranchseq_beg
        case 1: // __atstmplab4
        if(ATSCKptrisnull(tmp44)) {
          { tmplab_js = 4; break; }
        } // ifthen
        case 2: // __atstmplab5
        tmp45 = tmp44[0];
        // ATStailcalseq_beg
        apy0 = arg1;
        apy1 = tmp45;
        arg0 = apy0;
        arg1 = apy1;
        funlab_js = 1; // __patsflab_Wormlike_loop_17
        // ATStailcalseq_end
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        case 3: // __atstmplab6
        case 4: // __atstmplab7
        tmp47 = null;
        _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_set_tail(arg0, tmp47);
        tmpret43 = arg1;
        break;
        // ATSbranchseq_end
      } // end-of-switch
      if (tmplab_js === 0) break;
    } // endwhile
    // ATScaseofseq_end
    if (funlab_js > 0) continue; else return tmpret43;
  } // endwhile-fun
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_dats__worm_move(arg0, arg1)
{
//
// knd = 0
  var tmpret50
  var tmp51
  var tmp52
  var tmp53
  var tmp54
  var tmp56
  var tmp59
  var tmplab, tmplab_js
//
  // __patsflab_worm_move
  tmp51 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_pos(arg1);
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab8
      if(!ATSCKpat_con0(arg0, 0)) {
        { tmplab_js = 3; break; }
      } // ifnthen
      case 2: // __atstmplab9
      tmp52 = Wormlike_pos_x_dec_4(tmp51);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab10
      if(!ATSCKpat_con0(arg0, 1)) {
        { tmplab_js = 5; break; }
      } // ifnthen
      case 4: // __atstmplab11
      tmp52 = Wormlike_pos_x_inc_5(tmp51);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 5: // __atstmplab12
      if(!ATSCKpat_con0(arg0, 2)) {
        { tmplab_js = 7; break; }
      } // ifnthen
      case 6: // __atstmplab13
      tmp52 = Wormlike_pos_y_dec_6(tmp51);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 7: // __atstmplab14
      case 8: // __atstmplab15
      tmp52 = Wormlike_pos_y_inc_7(tmp51);
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  tmp53 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_length(arg1);
  tmp54 = ats2jspre_eq_int0_int0(tmp53, 1);
  if(tmp54) {
    _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_set_pos(arg1, tmp52);
    tmpret50 = arg1;
  } else {
    tmp56 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__worm_takeout_last(arg1);
    _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_set_pos(tmp56, tmp52);
    tmp59 = [arg1];
    _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_set_tail(tmp56, tmp59);
    tmpret50 = tmp56;
  } // end-of-if
  return tmpret50;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_dats__worm_movex(arg0, arg1)
{
//
// knd = 0
  var tmpret60
  var tmp61
  var tmp62
  var tmplab, tmplab_js
//
  // __patsflab_worm_movex
  tmp61 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_pos(arg1);
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab16
      if(!ATSCKpat_con0(arg0, 0)) {
        { tmplab_js = 3; break; }
      } // ifnthen
      case 2: // __atstmplab17
      tmp62 = Wormlike_pos_x_dec_4(tmp61);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab18
      if(!ATSCKpat_con0(arg0, 1)) {
        { tmplab_js = 5; break; }
      } // ifnthen
      case 4: // __atstmplab19
      tmp62 = Wormlike_pos_x_inc_5(tmp61);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 5: // __atstmplab20
      if(!ATSCKpat_con0(arg0, 2)) {
        { tmplab_js = 7; break; }
      } // ifnthen
      case 6: // __atstmplab21
      tmp62 = Wormlike_pos_y_dec_6(tmp61);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 7: // __atstmplab22
      case 8: // __atstmplab23
      tmp62 = Wormlike_pos_y_inc_7(tmp61);
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  tmpret60 = Wormlike_wnode_make_pos_tail_14(tmp62, arg1);
  return tmpret60;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_move_if(arg0)
{
//
// knd = 0
  var tmp64
  var tmp65
  var tmp66
  var tmp67
  var tmp68
  var tmp69
  var tmp70
  var tmp71
  var tmp72
  var tmp73
  var tmplab, tmplab_js
//
  // __patsflab_theWorm_move_if
  tmp64 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_get();
  tmp65 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_pos(tmp64);
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab24
      if(!ATSCKpat_con0(arg0, 0)) {
        { tmplab_js = 3; break; }
      } // ifnthen
      case 2: // __atstmplab25
      tmp66 = Wormlike_x_dec_0(tmp65[0]);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab26
      if(!ATSCKpat_con0(arg0, 1)) {
        { tmplab_js = 5; break; }
      } // ifnthen
      case 4: // __atstmplab27
      tmp66 = Wormlike_x_inc_1(tmp65[0]);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 5: // __atstmplab28
      tmp66 = tmp65[0];
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab29
      if(!ATSCKpat_con0(arg0, 2)) {
        { tmplab_js = 3; break; }
      } // ifnthen
      case 2: // __atstmplab30
      tmp67 = Wormlike_y_dec_2(tmp65[1]);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab31
      if(!ATSCKpat_con0(arg0, 3)) {
        { tmplab_js = 5; break; }
      } // ifnthen
      case 4: // __atstmplab32
      tmp67 = Wormlike_y_inc_3(tmp65[1]);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 5: // __atstmplab33
      tmp67 = tmp65[1];
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  tmp68 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_get();
  tmp69 = ats2jspre_mtrxszref_get_at(tmp68, tmp66, tmp67);
  tmp70 = ats2jspre_eq_int0_int0(tmp69, 0);
  if(tmp70) {
    _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_move(arg0);
  } else {
    tmp71 = ats2jspre_eq_int0_int0(tmp69, 1);
    if(tmp71) {
      _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_remove_last();
    } else {
      tmp72 = ats2jspre_eq_int0_int0(tmp69, 2);
      if(tmp72) {
        _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_remove_last();
      } else {
        tmp73 = ats2jspre_eq_int0_int0(tmp69, 3);
        if(tmp73) {
          _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_movex(arg0);
        } else {
          // ATSINSmove_void
        } // end-of-if
      } // end-of-if
    } // end-of-if
  } // end-of-if
  return/*_void*/;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_get()
{
//
// knd = 0
  var tmpret77
  var tmplab, tmplab_js
//
  // __patsflab_theWorm_get
  tmpret77 = ats2jspre_ref_get_elt(Wormlike_statmp74);
  return tmpret77;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_reset()
{
//
// knd = 0
  var tmp79
  var tmp80
  var tmplab, tmplab_js
//
  // __patsflab_theWorm_reset
  tmp80 = [0, 0];
  tmp79 = Wormlike_wnode_make_pos_13(tmp80);
  ats2jspre_ref_set_elt(Wormlike_statmp74, tmp79);
  return/*_void*/;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_remove_last()
{
//
// knd = 0
  var tmp82
  var tmplab, tmplab_js
//
  // __patsflab_theWorm_remove_last
  tmp82 = ats2jspre_ref_get_elt(Wormlike_statmp74);
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__worm_remove_last(tmp82);
  return/*_void*/;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_move(arg0)
{
//
// knd = 0
  var tmp84
  var tmp85
  var tmplab, tmplab_js
//
  // __patsflab_theWorm_move
  tmp85 = ats2jspre_ref_get_elt(Wormlike_statmp74);
  tmp84 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_dats__worm_move(arg0, tmp85);
  ats2jspre_ref_set_elt(Wormlike_statmp74, tmp84);
  return/*_void*/;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_movex(arg0)
{
//
// knd = 0
  var tmp87
  var tmp88
  var tmplab, tmplab_js
//
  // __patsflab_theWorm_movex
  tmp88 = ats2jspre_ref_get_elt(Wormlike_statmp74);
  tmp87 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_dats__worm_movex(arg0, tmp88);
  ats2jspre_ref_set_elt(Wormlike_statmp74, tmp87);
  return/*_void*/;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_get()
{
//
// knd = 0
  var tmpret90
  var tmplab, tmplab_js
//
  // __patsflab_theBoard_get
  tmpret90 = Wormlike_statmp89;
  return tmpret90;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_clear()
{
//
// knd = 0
  var tmp92
  var tmp93
  var tmplab, tmplab_js
//
  // __patsflab_theBoard_clear
  tmp92 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_get();
  tmp93 = ats2jspre_mtrxszref_foreach_method(tmp92);
  tmp93[0](tmp93, Wormlike_patsfun_28__closurerize(tmp92));
  return/*_void*/;
} // end-of-function


function
Wormlike_patsfun_28(env0, arg0, arg1)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_patsfun_28
  ats2jspre_mtrxszref_set_at(env0, arg0, arg1, 0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_insert_worm()
{
//
// knd = 0
  var tmp96
  var tmp104
  var tmplab, tmplab_js
//
  // __patsflab_theBoard_insert_worm
  tmp96 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_get();
  tmp104 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_get();
  Wormlike_loop_30(tmp96, tmp104);
  return/*_void*/;
} // end-of-function


function
Wormlike_loop_30(env0, arg0)
{
//
// knd = 1
  var apy0
  var tmp98
  var tmp99
  var tmp100
  var tmp102
  var tmp103
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_Wormlike_loop_30
    tmp98 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_pos(arg0);
    tmp99 = tmp98[0];
    tmp100 = tmp98[1];
    ats2jspre_mtrxszref_set_at(env0, tmp99, tmp100, 1);
    tmp102 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_tail(arg0);
    // ATScaseofseq_beg
    tmplab_js = 1;
    while(true) {
      tmplab = tmplab_js; tmplab_js = 0;
      switch(tmplab) {
        // ATSbranchseq_beg
        case 1: // __atstmplab34
        if(ATSCKptriscons(tmp102)) {
          { tmplab_js = 4; break; }
        } // ifthen
        case 2: // __atstmplab35
        // ATSINSmove_void
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        case 3: // __atstmplab36
        case 4: // __atstmplab37
        tmp103 = tmp102[0];
        // ATStailcalseq_beg
        apy0 = tmp103;
        arg0 = apy0;
        funlab_js = 1; // __patsflab_Wormlike_loop_30
        // ATStailcalseq_end
        break;
        // ATSbranchseq_end
      } // end-of-switch
      if (tmplab_js === 0) break;
    } // endwhile
    // ATScaseofseq_end
    if (funlab_js > 0) continue; else return/*_void*/;
  } // endwhile-fun
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_takeout_worm()
{
//
// knd = 0
  var tmp106
  var tmp107
  var tmplab, tmplab_js
//
  // __patsflab_theBoard_takeout_worm
  tmp106 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_get();
  tmp107 = ats2jspre_mtrxszref_foreach_method(tmp106);
  tmp107[0](tmp107, Wormlike_patsfun_32__closurerize(tmp106));
  return/*_void*/;
} // end-of-function


function
Wormlike_patsfun_32(env0, arg0, arg1)
{
//
// knd = 0
  var tmp109
  var tmp110
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_patsfun_32
  tmp110 = ats2jspre_mtrxszref_get_at(env0, arg0, arg1);
  tmp109 = ats2jspre_eq_int0_int0(tmp110, 1);
  if(tmp109) {
    ats2jspre_mtrxszref_set_at(env0, arg0, arg1, 0);
  } else {
    // ATSINSmove_void
  } // end-of-if
  return/*_void*/;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_initialize()
{
//
// knd = 0
  var tmp112
  var tmp113
  var tmp114
  var tmp115
  var tmp116
  var tmplab, tmplab_js
//
  // __patsflab_theBoard_initialize
  tmp112 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_get();
  tmp113 = ats2jspre_min_int1_int1(48, 48);
  tmp116 = ats2jspre_JSmath_random();
  tmp115 = ats2jspre_mul_int_double(tmp113, tmp116);
  tmp114 = ats2jspre_double2int(tmp115);
  Wormlike_add_particles_39(tmp112);
  return/*_void*/;
} // end-of-function


function
Wormlike_add_blocks_34(env0, env1, env2)
{
//
// knd = 0
  var tmp118
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_add_blocks_34
  tmp118 = ats2jspre_int_foreach_method(env1);
  tmp118[0](tmp118, Wormlike_patsfun_35__closurerize(env0, env1, env2));
  return/*_void*/;
} // end-of-function


function
Wormlike_patsfun_35(env0, env1, env2, arg0)
{
//
// knd = 0
  var tmp120
  var tmp121
  var tmp122
  var tmp123
  var tmp124
  var tmp126
  var tmp128
  var tmp129
  var tmp130
  var tmp131
  var tmp132
  var tmp133
  var tmp134
  var tmp135
  var tmp136
  var tmp137
  var tmp138
  var tmp139
  var tmp140
  var tmp141
  var tmp142
  var tmp143
  var tmp144
  var tmp145
  var tmp146
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_patsfun_35
  tmp121 = ats2jspre_div_int1_int1(env1, 2);
  tmp120 = ats2jspre_gt_int0_int0(env2, tmp121);
  if(tmp120) {
    tmp124 = ats2jspre_sub_int1_int1(env1, 5);
    tmp123 = ats2jspre_lt_int0_int0(arg0, tmp124);
    if(tmp123) {
      tmp122 = ats2jspre_gt_int0_int0(arg0, 5);
    } else {
      tmp122 = false;
    } // end-of-if
    if(tmp122) {
      ats2jspre_mtrxszref_set_at(env0, arg0, 5, 2);
      tmp126 = ats2jspre_gt_int0_int0(arg0, 5);
      if(tmp126) {
        tmp128 = ats2jspre_sub_int0_int0(env1, arg0);
        ats2jspre_mtrxszref_set_at(env0, tmp128, arg0, 2);
        tmp131 = ats2jspre_sub_int1_int1(env1, 10);
        tmp130 = ats2jspre_lt_int0_int0(arg0, tmp131);
        if(tmp130) {
          tmp129 = ats2jspre_gt_int0_int0(arg0, 18);
        } else {
          tmp129 = false;
        } // end-of-if
        if(tmp129) {
          ats2jspre_mtrxszref_set_at(env0, arg0, 20, 2);
        } else {
          // ATSINSmove_void
        } // end-of-if
      } else {
        // ATSINSmove_void
      } // end-of-if
    } else {
      // ATSINSmove_void
    } // end-of-if
  } else {
    tmp134 = ats2jspre_sub_int1_int1(env1, 15);
    tmp133 = ats2jspre_lt_int0_int0(arg0, tmp134);
    if(tmp133) {
      tmp132 = ats2jspre_gt_int0_int0(arg0, 15);
    } else {
      tmp132 = false;
    } // end-of-if
    if(tmp132) {
      ats2jspre_mtrxszref_set_at(env0, 26, arg0, 2);
    } else {
      tmp137 = ats2jspre_gt_int0_int0(arg0, 18);
      if(tmp137) {
        tmp140 = ats2jspre_pow_int0_int1(arg0, 2);
        tmp139 = ats2jspre_div_int0_int0(tmp140, 50);
        tmp138 = ats2jspre_neg_int0(tmp139);
        tmp136 = ats2jspre_lt_int0_int0(tmp138, env1);
      } else {
        tmp136 = false;
      } // end-of-if
      if(tmp136) {
        tmp143 = ats2jspre_pow_int0_int1(arg0, 2);
        tmp142 = ats2jspre_div_int0_int0(tmp143, 50);
        tmp141 = ats2jspre_sub_int0_int0(env1, tmp142);
        tmp135 = ats2jspre_gt_int0_int0(tmp141, 0);
      } else {
        tmp135 = false;
      } // end-of-if
      if(tmp135) {
        tmp146 = ats2jspre_pow_int0_int1(arg0, 2);
        tmp145 = ats2jspre_div_int0_int0(tmp146, 50);
        tmp144 = ats2jspre_sub_int0_int0(env1, tmp145);
        ats2jspre_mtrxszref_set_at(env0, tmp144, arg0, 2);
      } else {
        // ATSINSmove_void
      } // end-of-if
    } // end-of-if
  } // end-of-if
  return/*_void*/;
} // end-of-function


function
Wormlike_xrand_36()
{
//
// knd = 0
  var tmpret147
  var tmp148
  var tmp149
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_xrand_36
  tmp149 = ats2jspre_JSmath_random();
  tmp148 = ats2jspre_mul_int_double(48, tmp149);
  tmpret147 = ats2jspre_double2int(tmp148);
  return tmpret147;
} // end-of-function


function
Wormlike_yrand_37()
{
//
// knd = 0
  var tmpret150
  var tmp151
  var tmp152
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_yrand_37
  tmp152 = ats2jspre_JSmath_random();
  tmp151 = ats2jspre_mul_int_double(48, tmp152);
  tmpret150 = ats2jspre_double2int(tmp151);
  return tmpret150;
} // end-of-function


function
Wormlike_add_particle_38(env0)
{
//
// knd = 1
  var tmp154
  var tmp155
  var tmp156
  var tmp157
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_Wormlike_add_particle_38
    tmp154 = Wormlike_xrand_36();
    tmp155 = Wormlike_yrand_37();
    tmp156 = ats2jspre_mtrxszref_get_at(env0, tmp154, tmp155);
    tmp157 = ats2jspre_eq_int0_int0(tmp156, 0);
    if(tmp157) {
      ats2jspre_mtrxszref_set_at(env0, tmp154, tmp155, 3);
    } else {
      // ATStailcalseq_beg
      funlab_js = 1; // __patsflab_Wormlike_add_particle_38
      // ATStailcalseq_end
    } // end-of-if
    if (funlab_js > 0) continue; else return/*_void*/;
  } // endwhile-fun
} // end-of-function


function
Wormlike_add_particles_39(env0)
{
//
// knd = 0
  var tmp159
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_add_particles_39
  tmp159 = ats2jspre_int_repeat_method(50);
  tmp159[0](tmp159, Wormlike_patsfun_40__closurerize(env0));
  return/*_void*/;
} // end-of-function


function
Wormlike_patsfun_40(env0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_patsfun_40
  Wormlike_add_particle_38(env0);
  return/*_void*/;
} // end-of-function


function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_dats__theBoard_draw(arg0)
{
//
// knd = 0
  var tmp162
  var tmp163
  var tmp164
  var tmp165
  var tmp166
  var tmp167
  var tmp168
  var tmp169
  var tmp170
  var tmplab, tmplab_js
//
  // __patsflab_theBoard_draw
  tmp163 = ats2jspre_mul_double_int(1.0, 400);
  tmp162 = ats2jspre_div_double_int(tmp163, 48);
  tmp166 = ats2jspre_sub_int1_int1(600, 400);
  tmp165 = ats2jspre_mul_double_int(1.0, tmp166);
  tmp164 = ats2jspre_div_double_int(tmp165, 2);
  tmp169 = ats2jspre_sub_int1_int1(420, 400);
  tmp168 = ats2jspre_mul_double_int(1.0, tmp169);
  tmp167 = ats2jspre_div_double_int(tmp168, 2);
  tmp170 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_get();
  ats2js_HTML5_canvas2d_clearRect(arg0, 0, 0, 600, 420);
  Wormlike_auxrows_45(arg0, tmp162, tmp164, tmp167, "#000000", "#0000ff", "#ff0000", "#ffffff", tmp170, 0);
  return/*_void*/;
} // end-of-function


function
Wormlike_cget_42(env0, env1, env2, env3, arg0)
{
//
// knd = 0
  var tmpret171
  var tmp172
  var tmp173
  var tmp174
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_cget_42
  tmp172 = ats2jspre_eq_int0_int0(arg0, 1);
  if(tmp172) {
    tmpret171 = env0;
  } else {
    tmp173 = ats2jspre_eq_int0_int0(arg0, 2);
    if(tmp173) {
      tmpret171 = env1;
    } else {
      tmp174 = ats2jspre_eq_int0_int0(arg0, 3);
      if(tmp174) {
        tmpret171 = env2;
      } else {
        tmpret171 = env3;
      } // end-of-if
    } // end-of-if
  } // end-of-if
  return tmpret171;
} // end-of-function


function
Wormlike_auxone_43(env0, env1, env2, env3, env4, env5, env6, env7, env8, arg0, arg1)
{
//
// knd = 0
  var tmp176
  var tmp177
  var tmp178
  var tmp180
  var tmp183
  var tmp184
  var tmp185
  var tmp186
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_auxone_43
  tmp176 = ats2jspre_mtrxszref_get_at(env8, arg0, arg1);
  tmp177 = ats2jspre_eq_int0_int0(tmp176, 0);
  if(tmp177) {
    // ATSINSmove_void
  } else {
    tmp178 = ats2jspre_gt_int0_int0(tmp176, 0);
    if(tmp178) {
      tmp180 = Wormlike_cget_42(env4, env5, env6, env7, tmp176);
      ats2js_HTML5_canvas2d_set_fillStyle_string(env0, tmp180);
      ats2js_HTML5_canvas2d_beginPath(env0);
      tmp184 = ats2jspre_mul_int_double(arg0, env1);
      tmp183 = ats2jspre_add_double_double(env2, tmp184);
      tmp186 = ats2jspre_mul_int_double(arg1, env1);
      tmp185 = ats2jspre_add_double_double(env3, tmp186);
      ats2js_HTML5_canvas2d_rect(env0, tmp183, tmp185, env1, env1);
      ats2js_HTML5_canvas2d_closePath(env0);
      ats2js_HTML5_canvas2d_fill(env0);
    } else {
      // ATSINSmove_void
    } // end-of-if
  } // end-of-if
  return/*_void*/;
} // end-of-function


function
Wormlike_auxrow_44(env0, env1, env2, env3, env4, env5, env6, env7, env8, arg0, arg1)
{
//
// knd = 1
  var apy0
  var apy1
  var tmp189
  var tmp191
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_Wormlike_auxrow_44
    tmp189 = ats2jspre_lt_int0_int0(arg0, 48);
    if(tmp189) {
      Wormlike_auxone_43(env0, env1, env2, env3, env4, env5, env6, env7, env8, arg0, arg1);
      tmp191 = ats2jspre_add_int0_int0(arg0, 1);
      // ATStailcalseq_beg
      apy0 = tmp191;
      apy1 = arg1;
      arg0 = apy0;
      arg1 = apy1;
      funlab_js = 1; // __patsflab_Wormlike_auxrow_44
      // ATStailcalseq_end
    } else {
      // ATSINSmove_void
    } // end-of-if
    if (funlab_js > 0) continue; else return/*_void*/;
  } // endwhile-fun
} // end-of-function


function
Wormlike_auxrows_45(env0, env1, env2, env3, env4, env5, env6, env7, env8, arg0)
{
//
// knd = 1
  var apy0
  var tmp193
  var tmp195
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_Wormlike_auxrows_45
    tmp193 = ats2jspre_lt_int0_int0(arg0, 48);
    if(tmp193) {
      Wormlike_auxrow_44(env0, env1, env2, env3, env4, env5, env6, env7, env8, 0, arg0);
      tmp195 = ats2jspre_add_int0_int0(arg0, 1);
      // ATStailcalseq_beg
      apy0 = tmp195;
      arg0 = apy0;
      funlab_js = 1; // __patsflab_Wormlike_auxrows_45
      // ATStailcalseq_end
    } else {
      // ATSINSmove_void
    } // end-of-if
    if (funlab_js > 0) continue; else return/*_void*/;
  } // endwhile-fun
} // end-of-function


function
theAllAct_Next_do()
{
//
// knd = 0
  var tmp199
  var tmp202
  var tmplab, tmplab_js
//
  // __patsflab_theAllAct_Next_do
  tmp199 = 1;
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_move_if(tmp199);
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_takeout_worm();
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_insert_worm();
  tmp202 = theCanvas_ctx2d_get();
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_dats__theBoard_draw(tmp202);
  return/*_void*/;
} // end-of-function


function
theAllAct_Prev_do()
{
//
// knd = 0
  var tmp205
  var tmp208
  var tmplab, tmplab_js
//
  // __patsflab_theAllAct_Prev_do
  tmp205 = 0;
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_move_if(tmp205);
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_takeout_worm();
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_insert_worm();
  tmp208 = theCanvas_ctx2d_get();
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_dats__theBoard_draw(tmp208);
  return/*_void*/;
} // end-of-function


function
theAllAct_Next2_do()
{
//
// knd = 0
  var tmp211
  var tmp214
  var tmplab, tmplab_js
//
  // __patsflab_theAllAct_Next2_do
  tmp211 = 3;
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_move_if(tmp211);
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_takeout_worm();
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_insert_worm();
  tmp214 = theCanvas_ctx2d_get();
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_dats__theBoard_draw(tmp214);
  return/*_void*/;
} // end-of-function


function
theAllAct_Prev2_do()
{
//
// knd = 0
  var tmp217
  var tmp220
  var tmplab, tmplab_js
//
  // __patsflab_theAllAct_Prev2_do
  tmp217 = 2;
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_move_if(tmp217);
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_takeout_worm();
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_insert_worm();
  tmp220 = theCanvas_ctx2d_get();
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_dats__theBoard_draw(tmp220);
  return/*_void*/;
} // end-of-function


function
theAllAct_Random_do()
{
//
// knd = 0
  var tmp222
  var tmp223
  var tmp224
  var tmp225
  var tmp226
  var tmp227
  var tmplab, tmplab_js
//
  // __patsflab_theAllAct_Random_do
  tmp224 = ats2jspre_JSmath_random();
  tmp223 = ats2jspre_lte_double_double(tmp224, 0.5);
  if(tmp223) {
    tmp222 = 0;
  } else {
    tmp222 = 1;
  } // end-of-if
  tmp227 = ats2jspre_JSmath_random();
  tmp226 = ats2jspre_lte_double_double(tmp227, 0.5);
  if(tmp226) {
    tmp225 = 0;
  } else {
    tmp225 = 1;
  } // end-of-if
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab38
      if(!ATSCKpat_int(tmp222, 0)) {
        { tmplab_js = 4; break; }
      } // ifnthen
      case 2: // __atstmplab39
      if(!ATSCKpat_int(tmp225, 0)) {
        { tmplab_js = 4; break; }
      } // ifnthen
      case 3: // __atstmplab40
      theAllAct_Prev_do();
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 4: // __atstmplab41
      if(!ATSCKpat_int(tmp225, 0)) {
        { tmplab_js = 6; break; }
      } // ifnthen
      case 5: // __atstmplab42
      theAllAct_Next_do();
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 6: // __atstmplab43
      if(!ATSCKpat_int(tmp222, 0)) {
        { tmplab_js = 8; break; }
      } // ifnthen
      case 7: // __atstmplab44
      theAllAct_Prev2_do();
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 8: // __atstmplab45
      theAllAct_Next2_do();
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
theAllAct_Reset_do()
{
//
// knd = 0
  var tmp233
  var tmplab, tmplab_js
//
  // __patsflab_theAllAct_Reset_do
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_reset();
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_clear();
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_initialize();
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_insert_worm();
  tmp233 = theCanvas_ctx2d_get();
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_dats__theBoard_draw(tmp233);
  return/*_void*/;
} // end-of-function


function
Wormlike_x_dec_52(arg0)
{
//
// knd = 0
  var tmpret234
  var tmp235
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_x_dec_52
  tmp235 = ats2jspre_gt_int0_int0(arg0, 0);
  if(tmp235) {
    tmpret234 = ats2jspre_sub_int0_int0(arg0, 1);
  } else {
    tmpret234 = ats2jspre_sub_int1_int1(48, 1);
  } // end-of-if
  return tmpret234;
} // end-of-function


function
Wormlike_x_inc_53(arg0)
{
//
// knd = 0
  var tmpret236
  var tmp237
  var tmp238
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_x_inc_53
  tmp238 = ats2jspre_add_int0_int0(arg0, 1);
  tmp237 = ats2jspre_lt_int0_int0(tmp238, 48);
  if(tmp237) {
    tmpret236 = ats2jspre_add_int0_int0(arg0, 1);
  } else {
    tmpret236 = 0;
  } // end-of-if
  return tmpret236;
} // end-of-function


function
Wormlike_y_dec_54(arg0)
{
//
// knd = 0
  var tmpret239
  var tmp240
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_y_dec_54
  tmp240 = ats2jspre_gt_int0_int0(arg0, 0);
  if(tmp240) {
    tmpret239 = ats2jspre_sub_int0_int0(arg0, 1);
  } else {
    tmpret239 = ats2jspre_sub_int1_int1(48, 1);
  } // end-of-if
  return tmpret239;
} // end-of-function


function
Wormlike_y_inc_55(arg0)
{
//
// knd = 0
  var tmpret241
  var tmp242
  var tmp243
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_y_inc_55
  tmp243 = ats2jspre_add_int0_int0(arg0, 1);
  tmp242 = ats2jspre_lt_int0_int0(tmp243, 48);
  if(tmp242) {
    tmpret241 = ats2jspre_add_int0_int0(arg0, 1);
  } else {
    tmpret241 = 0;
  } // end-of-if
  return tmpret241;
} // end-of-function


function
theAllAct_Search_do()
{
//
// knd = 0
  var tmp315
  var tmp316
  var tmplab, tmplab_js
//
  // __patsflab_theAllAct_Search_do
  tmp315 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_get();
  tmp316 = Wormlike_theSearch_streamize_66__66__1();
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


function
Wormlike_theSearch_streamize_66__66__1()
{
//
// knd = 0
  var tmpret297__1
  var tmp298__1
  var tmp309__1
  var tmp310__1
  var tmp312__1
  var tmp313__1
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_theSearch_streamize_66
  tmp298__1 = ats2jspre_mtrxszref_make_elt(48, 48, 0);
  tmp309__1 = ats2jspre_qlistref_make_nil();
  tmp310__1 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theWorm_get();
  tmp313__1 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__wnode_pos(tmp310__1);
  tmp312__1 = _057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc2js_057_ATS2_055_0_056_3_056_2_057_SATS_057_ML_057_list0_056_sats__list0_sing__72__1(tmp313__1);
  ats2jspre_qlistref_enqueue(tmp309__1, tmp312__1);
  tmpret297__1 = _057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc2js_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__GraphStreamize_bfs__61__1(tmp298__1, tmp309__1);
  return tmpret297__1;
} // end-of-function


function
_057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc2js_057_ATS2_055_0_056_3_056_2_057_SATS_057_ML_057_list0_056_sats__list0_sing__72__1(arg0)
{
//
// knd = 0
  var tmpret324__1
  var tmp325__1
  var tmplab, tmplab_js
//
  // __patsflab_list0_sing
  tmp325__1 = null;
  tmpret324__1 = [arg0, tmp325__1];
  return tmpret324__1;
} // end-of-function


function
_057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc2js_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__GraphStreamize_bfs__61__1(env0, arg0)
{
//
// knd = 0
  var tmpret259__1
  var tmplab, tmplab_js
//
  // __patsflab_GraphStreamize_bfs
  tmpret259__1 = _057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__GraphStreamize__56__1(arg0, env0);
  return tmpret259__1;
} // end-of-function


function
_057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__GraphStreamize__56__1(env0, env1)
{
//
// knd = 0
  var tmpret244__1
  var tmplab, tmplab_js
//
  // __patsflab_GraphStreamize
  tmpret244__1 = Wormlike_streamize_57__57__1(env0, env1);
  return tmpret244__1;
} // end-of-function


function
Wormlike_streamize_57__57__1(env0, env1)
{
//
// knd = 0
  var tmpret245__1
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_streamize_57
  tmpret245__1 = ATSPMVlazyval(Wormlike_patsfun_58__58__1__closurerize(env0, env1));
  return tmpret245__1;
} // end-of-function


function
Wormlike_patsfun_58__58__1(env0, env1)
{
//
// knd = 0
  var tmpret246__1
  var tmp247__1
  var tmp248__1
  var tmp249__1
  var tmp251__1
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_patsfun_58
  tmp247__1 = _057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__theStreamizeStore_choose__60__1(env0);
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab46
      if(ATSCKptriscons(tmp247__1)) {
        { tmplab_js = 4; break; }
      } // ifthen
      case 2: // __atstmplab47
      tmpret246__1 = null;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab48
      case 4: // __atstmplab49
      tmp248__1 = tmp247__1[0];
      // ATSINSfreecon(tmp247__1);
      tmp249__1 = _057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__node_get_neighbors__65__1(tmp248__1);
      _057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__theStreamizeStore_insert_lst__63__1(env0, env1, tmp249__1);
      tmp251__1 = Wormlike_streamize_57__57__1(env0, env1);
      tmpret246__1 = [tmp248__1, tmp251__1];
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret246__1;
} // end-of-function


function
_057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__theStreamizeStore_choose__60__1(env0)
{
//
// knd = 0
  var tmpret257__1
  var tmp258__1
  var tmplab, tmplab_js
//
  // __patsflab_theStreamizeStore_choose
  tmp258__1 = _057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc2js_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__theStreamizeStore_get__62__1(env0);
  tmpret257__1 = ats2jspre_qlistref_dequeue_opt(tmp258__1);
  return tmpret257__1;
} // end-of-function


function
_057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc2js_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__theStreamizeStore_get__62__1(env0)
{
//
// knd = 0
  var tmpret260__1
  var tmplab, tmplab_js
//
  // __patsflab_theStreamizeStore_get
  tmpret260__1 = env0;
  return tmpret260__1;
} // end-of-function


function
_057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__node_get_neighbors__65__1(arg0)
{
//
// knd = 0
  var tmpret264__1
  var tmp265__1
  var tmp266__1
  var tmp267__1
  var tmp268__1
  var tmp269__1
  var tmp270__1
  var tmp271__1
  var tmp272__1
  var tmp273__1
  var tmp274__1
  var tmp275__1
  var tmp276__1
  var tmp277__1
  var tmp278__1
  var tmp279__1
  var tmp280__1
  var tmp281__1
  var tmp282__1
  var tmp283__1
  var tmp284__1
  var tmp285__1
  var tmp286__1
  var tmp287__1
  var tmp288__1
  var tmp289__1
  var tmp290__1
  var tmp291__1
  var tmp292__1
  var tmp293__1
  var tmp294__1
  var tmp295__1
  var tmp296__1
  var tmplab, tmplab_js
//
  // __patsflab_node_get_neighbors
  if(ATSCKptrisnull(arg0)) {
    ATSINScaseof_fail("/home/asmalldev/Sync/Code/Rosetta/ATS/brownian_tree/DATS_JS/theSearch.dats: 944(line=66, offs=1) -- 967(line=66, offs=24)");
  } // ifthen
  tmp265__1 = arg0[0];
  tmp266__1 = _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_sats__theBoard_get();
  tmp267__1 = tmp265__1[0];
  tmp268__1 = tmp265__1[1];
  tmp269__1 = null;
  tmp270__1 = Wormlike_x_dec_52(tmp267__1);
  tmp271__1 = ats2jspre_mtrxszref_get_at(tmp266__1, tmp270__1, tmp268__1);
  tmp274__1 = ats2jspre_eq_int0_int0(tmp271__1, 0);
  if(tmp274__1) {
    tmp273__1 = true;
  } else {
    tmp273__1 = ats2jspre_eq_int0_int0(tmp271__1, 3);
  } // end-of-if
  if(tmp273__1) {
    tmp276__1 = [tmp270__1, tmp268__1];
    tmp275__1 = [tmp276__1, arg0];
    tmp272__1 = [tmp275__1, tmp269__1];
  } else {
    tmp272__1 = tmp269__1;
  } // end-of-if
  tmp277__1 = Wormlike_x_inc_53(tmp267__1);
  tmp278__1 = ats2jspre_mtrxszref_get_at(tmp266__1, tmp277__1, tmp268__1);
  tmp281__1 = ats2jspre_eq_int0_int0(tmp278__1, 0);
  if(tmp281__1) {
    tmp280__1 = true;
  } else {
    tmp280__1 = ats2jspre_eq_int0_int0(tmp278__1, 3);
  } // end-of-if
  if(tmp280__1) {
    tmp283__1 = [tmp277__1, tmp268__1];
    tmp282__1 = [tmp283__1, arg0];
    tmp279__1 = [tmp282__1, tmp272__1];
  } else {
    tmp279__1 = tmp272__1;
  } // end-of-if
  tmp284__1 = Wormlike_y_dec_54(tmp268__1);
  tmp285__1 = ats2jspre_mtrxszref_get_at(tmp266__1, tmp267__1, tmp284__1);
  tmp288__1 = ats2jspre_eq_int0_int0(tmp285__1, 0);
  if(tmp288__1) {
    tmp287__1 = true;
  } else {
    tmp287__1 = ats2jspre_eq_int0_int0(tmp285__1, 3);
  } // end-of-if
  if(tmp287__1) {
    tmp290__1 = [tmp267__1, tmp284__1];
    tmp289__1 = [tmp290__1, arg0];
    tmp286__1 = [tmp289__1, tmp279__1];
  } else {
    tmp286__1 = tmp279__1;
  } // end-of-if
  tmp291__1 = Wormlike_y_inc_55(tmp268__1);
  tmp292__1 = ats2jspre_mtrxszref_get_at(tmp266__1, tmp267__1, tmp291__1);
  tmp294__1 = ats2jspre_eq_int0_int0(tmp292__1, 0);
  if(tmp294__1) {
    tmp293__1 = true;
  } else {
    tmp293__1 = ats2jspre_eq_int0_int0(tmp292__1, 3);
  } // end-of-if
  if(tmp293__1) {
    tmp296__1 = [tmp267__1, tmp291__1];
    tmp295__1 = [tmp296__1, arg0];
    tmpret264__1 = [tmp295__1, tmp286__1];
  } else {
    tmpret264__1 = tmp286__1;
  } // end-of-if
  return tmpret264__1;
} // end-of-function


function
_057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__theStreamizeStore_insert_lst__63__1(env0, env1, arg0)
{
//
// knd = 0
  var tmp262__1
  var tmplab, tmplab_js
//
  // __patsflab_theStreamizeStore_insert_lst
  tmp262__1 = ats2jspre_ML_list0_foreach_method(arg0);
  tmp262__1[0](tmp262__1, Wormlike_patsfun_64__64__1__closurerize(env0, env1));
  return/*_void*/;
} // end-of-function


function
Wormlike_patsfun_64__64__1(env0, env1, arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_Wormlike_patsfun_64
  _057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__theStreamizeStore_insert__59__1(env0, env1, arg0);
  return/*_void*/;
} // end-of-function


function
_057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__theStreamizeStore_insert__59__1(env0, env1, arg0)
{
//
// knd = 0
  var tmp253__1
  var tmp254__1
  var tmp255__1
  var tmplab, tmplab_js
//
  // __patsflab_theStreamizeStore_insert
  tmp253__1 = _057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc2js_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__theStreamizeStore_get__62__2(env0);
  tmp255__1 = _057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc2js_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__node_is_marked__69__1(env1, arg0);
  tmp254__1 = ats2jspre_neg_bool0(tmp255__1);
  if(tmp254__1) {
    _057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc2js_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__node_mark__67__1(env1, arg0);
    ats2jspre_qlistref_enqueue(tmp253__1, arg0);
  } else {
    // ATSINSmove_void
  } // end-of-if
  return/*_void*/;
} // end-of-function


function
_057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc2js_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__theStreamizeStore_get__62__2(env0)
{
//
// knd = 0
  var tmpret260__2
  var tmplab, tmplab_js
//
  // __patsflab_theStreamizeStore_get
  tmpret260__2 = env0;
  return tmpret260__2;
} // end-of-function


function
_057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc2js_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__node_is_marked__69__1(env0, arg0)
{
//
// knd = 0
  var tmpret304__1
  var tmp305__1
  var tmp306__1
  var tmp307__1
  var tmp308__1
  var tmplab, tmplab_js
//
  // __patsflab_node_is_marked
  if(ATSCKptrisnull(arg0)) {
    ATSINScaseof_fail("/home/asmalldev/Sync/Code/Rosetta/ATS/brownian_tree/DATS_JS/theSearch.dats: 2148(line=144, offs=1) -- 2181(line=145, offs=23)");
  } // ifthen
  tmp305__1 = arg0[0];
  tmp306__1 = tmp305__1[0];
  tmp307__1 = tmp305__1[1];
  tmp308__1 = ats2jspre_mtrxszref_get_at(env0, tmp306__1, tmp307__1);
  tmpret304__1 = ats2jspre_eq_int0_int0(tmp308__1, 1);
  return tmpret304__1;
} // end-of-function


function
_057_usr_057_lib_057_ats2_055_postiats_055_0_056_3_056_6_057_contrib_057_libatscc2js_057_ATS2_055_0_056_3_056_2_057_DATS_057_BUCS320_057_GraphStreamize_057_GraphStreamize_bfs_056_dats__node_mark__67__1(env0, arg0)
{
//
// knd = 0
  var tmp300__1
  var tmp301__1
  var tmp302__1
  var tmplab, tmplab_js
//
  // __patsflab_node_mark
  if(ATSCKptrisnull(arg0)) {
    ATSINScaseof_fail("/home/asmalldev/Sync/Code/Rosetta/ATS/brownian_tree/DATS_JS/theSearch.dats: 1974(line=130, offs=1) -- 2007(line=131, offs=23)");
  } // ifthen
  tmp300__1 = arg0[0];
  tmp301__1 = tmp300__1[0];
  tmp302__1 = tmp300__1[1];
  ats2jspre_mtrxszref_set_at(env0, tmp301__1, tmp302__1, 1);
  return/*_void*/;
} // end-of-function

// dynloadflag_minit
var _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_dats__dynloadflag = 0;

function
_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_dats__dynload()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // ATSdynload()
  // ATSdynloadflag_sta(_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_dats__dynloadflag(601))
  if(ATSCKiseqz(_057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_dats__dynloadflag)) {
    _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_dats__dynloadflag = 1 ; // flag is set
    Wormlike_statmp76 = [0, 0];
    Wormlike_statmp75 = Wormlike_wnode_make_pos_13(Wormlike_statmp76);
    Wormlike_statmp74 = ats2jspre_ref(Wormlike_statmp75);
    Wormlike_statmp89 = ats2jspre_mtrxszref_make_elt(48, 48, 0);
  } // end-of-if
  return/*_void*/;
} // end-of-function


function
Wormlike_initize()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  _057_home_057_asmalldev_057_Sync_057_Code_057_Rosetta_057_ATS_057_brownian_tree_057_DATS_JS_057_main_056_dats__dynload();
  return/*_void*/;
} // end-of-function


/* ATSextcode_beg() */
//
Wormlike_initize(/*void*/);
//
/* ATSextcode_end() */

/* ****** ****** */

/* end-of-compilation-unit */
